### ISSUE TITLE
Generate Mutation: not creating correct input variables

### ISSUE THREAD

**Issue by astanciu** [shahankit/custom-graphiql#4]
When generating a mutation, it does not create the right inputs:
![image](https://cloud.githubusercontent.com/assets/1675025/22489962/5ce5c0bc-e7e8-11e6-959c-46ed32faf477.png)

input_0 should be the object for `RequestInput` type.

Side note, the items with the red underline... not sure if those should be expanded (which could go very deep, if not infinitely deep in some cases), or excluded.

**Comment by shahankit** [comment]
Hello Alex, can you please share test schema for reproducing this issue.

**Comment by astanciu** [comment]
Sure:


Mutation:
```
createRequest(request: RequestInput!): Request
```

Input:
```
  input RequestInput{
    requester: String!
    beneficiary: String!
    resources: [RequestResourceInput!]!
    notes: String
  }

  input RequestResourceInput{
    uuid: String!
    data: JSON
  }
```

Others:
```
  type Request {
    uuid: String
    requester: User
    beneficiary: User
    resources: [RequestedResourceEntry]
    status: String
    created_at: Date
    updated_at: Date
    notes: String
    number: Int
    last_error: String
  }

type RequestedResourceEntry{
    resource: RequestedResource
    approvals: [ResourceApproval]
    status: String
    fulfillment_user: JSON
    fulfillment_group: JSON
    fulfilled_by: User
    fulfilled_at: Date
    data: JSON
  }

  type ResourceApproval{
    order: Int
    name: String
    approver_user: JSON
    approver_group: JSON
    approved_by: User
    approved_at: Date
    notification: String
    status: String
  }
```

**Comment by shahankit** [comment]
@astanciu Sorry for late reply. I've fixed the issue where input_0 was not getting generated. You didn't provide any schema for User so I supposed it to be an object with uuid. Following is the screenshot for the generated mutation:

![screen shot 2017-02-18 at 4 37 02 pm](https://cloud.githubusercontent.com/assets/4739743/23092795/a168fa56-f5f8-11e6-8a36-9b43a1f46bb7.png)

Please do check and let me know if the problem persists, otherwise feel free to close the issue.
